version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - POSTGREST_USERNAME=${POSTGREST_USERNAME}
      - POSTGREST_PASSWORD=${POSTGREST_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5433
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGREST_USERNAME}
      - POSTGRES_PASSWORD=${POSTGREST_PASSWORD}
      - POSTGRES_DB=memedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: